install:
  - |
    export TAG="$(curl -H "Authorization: token $GITHUB_API_TOKEN" --silent "https://api.github.com/repos/dzen-dhall/dzen-dhall/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
    export PATH="$HOME/:$PATH"
    wget -O $HOME/dzen-dhall.tar.gz https://github.com/dzen-dhall/dzen-dhall/releases/download/$TAG/linux.tar.gz
    tar -xvf $HOME/dzen-dhall.tar.gz -C $HOME/
    chmod a+x $HOME/dzen-dhall

script:
  - |
    CI=1 ./check.sh
